server: 
  port: 8080
---
spring:
  profiles: dev,local
  data:
    rest:
      base-path: api
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
    username: sa
    password: nabtest
    platform: org.hibernate.dialect.H2Dialect
